version: 2
jobs:
  Python_2.7:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7

    working_directory: ~/repo

    steps: &steps
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            mkdir -p ./venv
            virtualenv ./venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run script
          # make sure the script runs, set a 60s timeout
          command: |
            . venv/bin/activate
            python --version
            pip --version
            python noisy.py --config config.json --timeout 60

      - store_artifacts:
          path: test-reports
          destination: test-reports

  Python_3.6:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps: *steps

  Python_3.7:
    docker:
      - image: circleci/python:3.7-rc-node
    working_directory: ~/repo
    steps: *steps

workflows:
  version: 2
  build:
    jobs:
      - Python_2.7
      - Python_3.6
      - Python_3.7
